# vim: set ft=yaml ts=2 expandtab:
---

- name: converge {{ cookiecutter.collection_name }}
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: {{ cookiecutter.collection_namespace }}.{{ cookiecutter.collection_name }}.{{ cookiecutter.collection_name }}

  tasks:

  - name: test
    fail:

...
