# Copyright (c) {% now 'utc', '%Y' %} {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
# SPDX-License-Identifier: {{ cookiecutter.license }}
# see LICENSE or https://spdx.org/licenses/{{ cookiecutter.license }}.html
---

- name: converge {{ cookiecutter.collection_name }}
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: {{ cookiecutter.collection }}.role1

  tasks:

  - name: test
    fail:

...
