# Copyright (c) {% now 'utc', '%Y' %} {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
# SPDX-License-Identifier: {{ cookiecutter.license }}
# see LICENSE or https://spdx.org/licenses/{{ cookiecutter.license }}.html
---

- name: Set up proxy
  hosts: proxy_group

  pre_tasks:

  # https://github.com/geerlingguy/ansible-role-composer/issues/54
  #
  - name: get status of systemd-tmpfiles-setup.service # noqa 303
    command: systemctl status systemd-tmpfiles-setup.service
    when: ansible_service_mgr == 'systemd'
    changed_when: false

  roles:

  - name: mafalb.squid.server

...
