# vim: set ft=yaml ts=2 expandtab:
---

- hosts: all
  tasks:

  - name: create an ansible collection
    command: cookiecutter --config-file files/httpd.yaml --no-input ../../collection -o /tmp/ansible_collections/example
    args:
      creates: /tmp/ansible_collections/example/httpd

  - name: create a molecule scenario
    command: cookiecutter -f --config-file /tmp/ansible_collections/example/httpd/cookiecutter.yaml --no-input ../../molecule -o /tmp/ansible_collections/example/httpd
    args:
      creates: /tmp/ansible_collections/example/httpd/molecule

  - name: create github-actions
    command: cookiecutter -f --config-file /tmp/ansible_collections/example/httpd/cookiecutter.yaml --no-input ../../github-actions -o /tmp/ansible_collections/example/httpd
    args:
      creates: /tmp/ansible_collections/example/httpd/.github/workflows/CI.yml

  - name: create a role
    command: cookiecutter -f --config-file /tmp/ansible_collections/example/httpd/cookiecutter.yaml --config-file files/role1.yaml --no-input -o /tmp/ansible_collections/example/httpd/roles ../../role role=example.httpd.role1
    args:
      creates: /tmp/ansible_collections/example/httpd/roles/role1

  - name: create a standalone role
    command: cookiecutter --config-file files/standalone-role.yaml --no-input ../../role -o /tmp role=example.role1
    args:
      creates: /tmp/example.rolex

...
