# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml

lint: |
  set -e
  pwd
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v molecule/default/*.yml --exclude molecule/default/molecule.yml
  flake8 -v

driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: ci

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
  lint:
    name: ansible-lint

verifier:
  name: ansible

...
