# Copyright (c) {% now 'utc', '%Y' %} {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>
# SPDX-License-Identifier: {{ cookiecutter.license }}
# see LICENSE or https://spdx.org/licenses/{{ cookiecutter.license }}.html
---

# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric characters and underscores. Additionally namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: {{ cookiecutter.namespace }}

# The name of the collection. Has the same character restrictions as 'namespace'
name: {{ cookiecutter.collection_name }}

# The version of the collection. Must be compatible with semantic versioning
version: 0.0.1

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
- {{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>


### OPTIONAL but strongly recommended

# A short summary description of the collection
description: Ansible collection {{ cookiecutter.collection }}

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
- {{ cookiecutter.license }}

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
- {{ cookiecutter.collection_name }}

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

# The URL of the originating SCM repository
repository: {{ cookiecutter.repository_url }}

# The URL to any online docs
documentation: {{ cookiecutter.repository_url }}

# The URL to the homepage of the collection/project
homepage: {{ cookiecutter.repository_url }}

{% if cookiecutter.hosted_by == 'github' %}
# The URL to the collection issue tracker
issues: {{ cookiecutter.repository_url }}/issues
{% else %}
# The URL to the collection issue tracker
issues: {{ cookiecutter.repository_url }}
{% endif %}
...
