# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 5'

jobs:

  CI:

    runs-on: ubuntu-20.04

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        pip3 install cookiecutter flake8

    - name: tests
      run: |
        pwd
        ls -l
        export PATH=$PATH:~/.local/bin
        tests/lint.sh
        ansible-playbook tests/converge.yml

...
