# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 5'

jobs:

  CI:

    runs-on: ubuntu-20.04

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        ansible-galaxy collection install mafalb.ansible
        ansible-playbook -D molecule/install_molecule.yml -t all,debug

    - name: tests
      run: |
        pwd
        ls -l
        bash tests/lint.sh

...
